/// Flutter icons Ubenwa
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Ubenwa
///      fonts:
///       - asset: fonts/Ubenwa.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Ubenwa {
  Ubenwa._();

  static const _kFontFam = 'Ubenwa';
  static const String _kFontPkg = null;

  static const IconData normal_user =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clinical_user =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
